tasks: Ensure /etc/keystone/credential-keys is created on time
We need to ensure that {{ keystone_credential_key_repository }} is
created along with the rest of directories in order to prevent problems
like the following one:

OSError: [Errno 2] No such file or directory: '/etc/keystone/credential-keys'

Depends-On: I5a78e2120e596d36629b4ba978b2b5df76b149b0
Change-Id: I394e069f9cbea7b85e5f6f53e3d3f9f54494dafe